apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-ktmhwcda
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-quarkus-ktmhwcda:6191a84fd37d746c962e1b4a1b996a5f40bb276e@sha256:5e331ff7e062b168d23be872756907c718604418963178f9d821dc2fd2ef5d71
          name: container-image
